const COURSE={label:"3ro Técnico",specialty:"Bachillerato Técnico Contable",period:"2026-2027",institution:"Unidad Educativa Particular Lev Vigotsky"};
const STUDENTS=[
{n:1,name:"ALCÍVAR CEDEÑO GÉNESSIS ANALÍA"},{n:2,name:"ANDRADE LARA MATIAS SEBASTIAN"},{n:3,name:"BAILÓN ESTRADA DILLAN SANTIAGO"},{n:4,name:"CAÑARTE CASTRO FREDDY MATHIAS"},{n:5,name:"CARREÑO MENDOZA KEILA ANAHÍ"},{n:6,name:"CASTRELLON VERA ISMAEL"},{n:7,name:"CEDEÑO QUIJIJE MATEO"},{n:8,name:"CEDEÑO VASQUEZ MARCO ANDRES"},{n:9,name:"CEVALLOS COBEÑA JOSE MATIAS"},{n:10,name:"CEVALLOS LOPEZ SHIRLEY VALERIA"},{n:11,name:"CEVALLOS YOSA EMILY SCARLETH"},{n:12,name:"DELGADO MERO MAYKEL DARIAN"},{n:13,name:"DUARTE AVEIGA CRISTHIAN VALENTIN"},{n:14,name:"FALCONI MERO VIELKA ROMINA"},{n:15,name:"FRANCO FRANCO LUISANA VALENTINA"},{n:16,name:"LOOR OCHOA JOHAN PAUL"},{n:17,name:"MACIAS TUBAY ANGELA DAMARYS"},{n:18,name:"MASAPANTA ZAMBRANO JEAN MARCOS"},{n:19,name:"MEDRANDA PONCE MELANY YANOSKA"},{n:20,name:"MEJIA LOPEZ GERALD JOHAN"},{n:21,name:"MENDOZA CAJAMARCA HANNA MICHELLE"},{n:22,name:"MORRILLO CORDERO MIGUEL ANGEL"},{n:23,name:"MUÑOZ SUAREZ BRANDON DARIO"},{n:24,name:"NAULA SÁNCHEZ NOHELIA VALEZKA"},{n:25,name:"PELAEZ SABANDO KEYLA DAMARIS"},{n:26,name:"PIGUAVE BARREZUETA ANGIE NAYIBETH"},{n:27,name:"REYES MERA RANDY ELIAN"},{n:28,name:"REYES SABANDO BRITHANY PAMELA"},{n:29,name:"RODRÍGUEZ URDÁNIGO BRUNO ABDÓN"},{n:30,name:"SANTANA MEJIA SARA NAHOMY"},{n:31,name:"TUMBACO MACÍAS JUAN DAVID"},{n:32,name:"VELASCO REYES MILAGROS ANALIA"},{n:33,name:"VERA MOREIRA BIANKA MILENA"},{n:34,name:"VERA PILAY JHON WALTER"},{n:35,name:"VIDAL FREYA MELINA"},{n:36,name:"ZAMORA ESCALANTE MATIAS BENJAMIN"}
];
const RUBRIC=[
{id:"tiempo",title:"Tiempo",max:1,options:[{value:1,label:"El estudiante cumple con el tiempo establecido de 2:00 a 3 minutos."},{value:.5,label:"El estudiante se pasa del tiempo estipulado."},{value:.25,label:"El estudiante no se ha preparado y no cumple con lo solicitado."}]},
{id:"preparacion",title:"Preparación",max:2,options:[{value:2,label:"Se nota buen dominio del tema, no comete errores y no duda."},{value:1.5,label:"Exposición fluida con muy pocos errores."},{value:1,label:"Hace algunas rectificaciones y de vez en cuando parece dudar."}]},
{id:"interes",title:"Interés",max:2,options:[{value:2,label:"Atrae la atención de los asistentes y mantiene el interés durante toda la exposición."},{value:1.5,label:"Interesante al principio, pero se vuelve monótona."},{value:1,label:"Le cuesta mantener el interés de los compañeros."}]},
{id:"voz",title:"Voz",max:2,options:[{value:2,label:"Buena vocalización, entonación adecuada, matizada y buen timbre de voz."},{value:1.5,label:"Buena vocalización, pero con timbre de voz bajo."},{value:1,label:"Cuesta comprender algunos fragmentos."}]},
{id:"expresion",title:"Expresión corporal y seguridad",max:2,options:[{value:2,label:"Su postura, gestos y contacto visual son adecuados y seguros."},{value:1.5,label:"Mantiene postura correcta y gestos adecuados, pero le falta contacto visual."},{value:.5,label:"Se mantuvo nervioso o tenso durante toda la exposición."}]},
{id:"soporte",title:"Soporte",max:1,options:[{value:1,label:"La exposición se acompaña con materiales adecuados, atractivos y de calidad."},{value:.5,label:"Soporte didáctico poco interesante."},{value:.25,label:"Soporte didáctico inadecuado."}]}
];
const QUICK_NOTES=["Cumple con el tiempo","Buen dominio del tema","Exposición clara","Mantiene el interés","Buena vocalización","Contacto visual adecuado","Material de apoyo adecuado","Debe mejorar la seguridad","Debe controlar mejor el tiempo","Debe fortalecer el soporte visual"];
const KEY="lv_sustentacion_fct_3ro_tecnico_2026_v1";
const $=s=>document.querySelector(s);
const els={activity:$("#activityInput"),date:$("#dateInput"),search:$("#studentSearch"),select:$("#studentSelect"),status:$("#studentStatus"),rubric:$("#rubricList"),score:$("#scoreValue"),scoreStatus:$("#scoreStatus"),ring:$("#scoreRing"),notes:$("#quickNotes"),comment:$("#teacherComment"),assessed:$("#statAssessed"),pending:$("#statPending"),avg:$("#statAverage"),dialog:$("#historyDialog"),history:$("#historyList"),toast:$("#toast")};
let store=loadStore(),current=1,toastTimer=null,quiet=false;
function loadStore(){try{return JSON.parse(localStorage.getItem(KEY)||"{}")||{}}catch{return {}}}
function writeStore(){localStorage.setItem(KEY,JSON.stringify(store))}
function today(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}
function student(n=current){return STUDENTS.find(s=>s.n===Number(n))||STUDENTS[0]}
function defaultCriteria(){return Object.fromEntries(RUBRIC.map(c=>[c.id,c.options[0].value]))}
function record(n=current){const s=student(n),r=store[String(s.n)]||{};return{studentNumber:s.n,studentName:s.name,activity:els.activity?.value||"Sustentación de Prácticas Preprofesionales (FCT)",date:today(),criteria:defaultCriteria(),notes:[],comment:"",evaluated:false,savedAt:null,...r,criteria:{...defaultCriteria(),...(r.criteria||{})},notes:Array.isArray(r.notes)?r.notes:[]}}
function save(n=current,r){store[String(n)]={...r,studentNumber:Number(n),studentName:student(n).name};writeStore();stats();renderOptions()}
function fmt(v){const r=Math.round(Number(v||0)*100)/100;return Number.isInteger(r)?String(r):String(r).replace(".",",")}
function total(r){return RUBRIC.reduce((s,c)=>s+Number(r.criteria?.[c.id]??c.options[0].value),0)}
function option(c,v){return c.options.find(o=>Number(o.value)===Number(v))||c.options[0]}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function dateFmt(v){const [y,m,d]=String(v||"").split("-");return d&&m&&y?`${d}/${m}/${y}`:String(v||"")}
function dateTime(v){try{return new Intl.DateTimeFormat("es-EC",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v))}catch{return String(v||"")}}
function norm(t){return String(t||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim()}
function readCriteria(){const out={};RUBRIC.forEach(c=>{const x=document.querySelector(`input[name="criterion-${c.id}"]:checked`);out[c.id]=x?Number(x.value):c.options[0].value});return out}
function readNotes(){return Array.from(document.querySelectorAll(".note-chip.active")).map(b=>b.dataset.note)}
function draft(mark=false){const old=record(current);const r={...old,activity:els.activity.value.trim()||"Sustentación de Prácticas Preprofesionales (FCT)",date:els.date.value||today(),comment:els.comment.value.trim(),criteria:readCriteria(),notes:readNotes(),evaluated:mark?true:old.evaluated,savedAt:mark?new Date().toISOString():old.savedAt};save(current,r);updateScore(r);status(r);return r}
function renderOptions(){const q=norm(els.search.value);const list=q?STUDENTS.filter(s=>norm(`${s.n} ${s.name}`).includes(q)):STUDENTS;els.select.innerHTML="";(list.length?list:STUDENTS).forEach(s=>{const o=document.createElement("option");o.value=s.n;o.textContent=`${s.n}. ${s.name}${record(s.n).evaluated?" ✓":""}`;els.select.appendChild(o)});if([...els.select.options].some(o=>Number(o.value)===current))els.select.value=current;else if(els.select.options.length)els.select.selectedIndex=0}
function renderRubric(r=record()){els.rubric.innerHTML="";RUBRIC.forEach(c=>{const card=document.createElement("article");card.className="rubric-card";const v=Number(r.criteria?.[c.id]??c.options[0].value);card.innerHTML=`<div class="rubric-title"><h4>${esc(c.title)}</h4><span>Máx. ${fmt(c.max)} punto${c.max===1?"":"s"}</span></div><div class="option-list">${c.options.map(o=>`<label class="option-row ${Number(o.value)===v?"selected":""}"><input type="radio" name="criterion-${c.id}" value="${o.value}" ${Number(o.value)===v?"checked":""}/><span class="option-text">${esc(o.label)}</span><span class="option-points">${fmt(o.value)}</span></label>`).join("")}</div>`;card.querySelectorAll("input").forEach(input=>input.addEventListener("change",()=>{card.querySelectorAll(".option-row").forEach(row=>row.classList.remove("selected"));input.closest(".option-row").classList.add("selected");draft(false)}));els.rubric.appendChild(card)})}
function renderNotes(r=record()){const active=new Set(r.notes||[]);els.notes.innerHTML="";QUICK_NOTES.forEach(note=>{const b=document.createElement("button");b.type="button";b.className=`note-chip${active.has(note)?" active":""}`;b.dataset.note=note;b.textContent=note;b.onclick=()=>{b.classList.toggle("active");draft(false)};els.notes.appendChild(b)})}
function updateScore(r=record()){const t=total(r),p=Math.round(t*10);els.score.textContent=`${fmt(t)} / 10`;els.scoreStatus.textContent=t>=9?"Desempeño destacado":t>=7?"Desempeño satisfactorio":t>=5?"Requiere refuerzo":"Requiere acompañamiento";els.ring.textContent=`${p}%`;els.ring.style.background=`conic-gradient(var(--gold) ${Math.max(0,Math.min(100,p))*3.6}deg, rgba(255,255,255,.18) 0deg)`}
function status(r=record()){els.status.classList.toggle("saved",!!r.evaluated);els.status.classList.toggle("pending",!r.evaluated);els.status.textContent=r.evaluated?"Guardado":"Pendiente"}
function stats(){const rs=STUDENTS.map(s=>record(s.n));const done=rs.filter(r=>r.evaluated);const avg=done.length?done.reduce((a,r)=>a+total(r),0)/done.length:0;els.assessed.textContent=done.length;els.pending.textContent=STUDENTS.length-done.length;els.avg.textContent=done.length?`${fmt(avg)} / 10`:"—"}
function load(n){draft(false);current=Number(n);const r=record(current);quiet=true;els.activity.value=r.activity;els.date.value=r.date;els.comment.value=r.comment;renderRubric(r);renderNotes(r);updateScore(r);status(r);renderOptions();quiet=false}
function report(mark=false){const r=draft(mark),s=student(current),lines=["RÚBRICA DE SUSTENTACIÓN DE PRÁCTICA PREPROFESIONAL",COURSE.institution,`${COURSE.label} · ${COURSE.specialty}`,`Período lectivo: ${COURSE.period}`,"",`Estudiante: ${s.n}. ${s.name}`,`Actividad: ${r.activity}`,`Fecha: ${dateFmt(r.date)}`,`Puntaje total: ${fmt(total(r))} / 10`,"","Detalle de criterios:"];RUBRIC.forEach(c=>{const v=Number(r.criteria[c.id]),o=option(c,v);lines.push(`- ${c.title}: ${fmt(v)} / ${fmt(c.max)} — ${o.label}`)});if(r.notes.length)lines.push("",`Observaciones rápidas: ${r.notes.join(" · ")}`);if(r.comment)lines.push("",`Comentario: ${r.comment}`);return lines.join("\n")}
function toast(msg){clearTimeout(toastTimer);els.toast.textContent=msg;els.toast.classList.add("show");toastTimer=setTimeout(()=>els.toast.classList.remove("show"),1800)}
function copyText(text){navigator.clipboard?.writeText(text).catch(()=>{const a=document.createElement("textarea");a.value=text;document.body.appendChild(a);a.select();document.execCommand("copy");a.remove()})}
function rows(only=false){return STUDENTS.map(s=>{const r=record(s.n);return{student:s,record:r,total:total(r),status:r.evaluated?"Evaluado":"Pendiente"}}).filter(x=>only?x.record.evaluated:true)}
function csvCell(v){return `"${String(v??"").replace(/"/g,'""')}"`}
function csv(rs){const h=["No.","Estudiante","Curso","Especialidad","Actividad","Fecha","Estado","Puntaje total"];RUBRIC.forEach(c=>h.push(`${c.title} - puntaje`,`${c.title} - descriptor`));h.push("Observaciones rápidas","Comentario","Guardado en");const out=[h.map(csvCell).join(",")];rs.forEach(({student:s,record:r,total:t,status})=>{const row=[s.n,s.name,COURSE.label,COURSE.specialty,r.activity,dateFmt(r.date),status,status==="Evaluado"?fmt(t):""];RUBRIC.forEach(c=>{const v=Number(r.criteria[c.id]),o=option(c,v);row.push(status==="Evaluado"?fmt(v):"",status==="Evaluado"?o.label:"")});row.push(status==="Evaluado"?r.notes.join(" · "):"",status==="Evaluado"?r.comment:"",r.savedAt?dateTime(r.savedAt):"");out.push(row.map(csvCell).join(","))});return out.join("\n")}
function download(content,name,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),800)}
function exportCsv(all=true){download("\ufeff"+csv(rows(!all)),`rubrica-sustentacion-${all?"3ro-tecnico":"guardados"}-${new Date().toISOString().slice(0,10)}.csv`,"text/csv;charset=utf-8");toast("CSV exportado")}
function printable(rs,title){const done=rs.filter(x=>x.record.evaluated),avg=done.length?done.reduce((a,x)=>a+x.total,0)/done.length:0;const main=rs.map(({student:s,record:r,total:t,status})=>`<tr class="${status==="Pendiente"?"pending":""}"><td>${s.n}</td><td><b>${esc(s.name)}</b></td><td>${status}</td><td>${status==="Evaluado"?fmt(t):"—"}</td><td>${status==="Evaluado"?esc(r.notes.join(" · ")):""}</td><td>${status==="Evaluado"?esc(r.comment):""}</td></tr>`).join("");const det=done.map(({student:s,record:r,total:t})=>`<h3>${s.n}. ${esc(s.name)} — ${fmt(t)} / 10</h3><table><thead><tr><th>Criterio</th><th>Descriptor</th><th>Puntaje</th></tr></thead><tbody>${RUBRIC.map(c=>{const v=Number(r.criteria[c.id]),o=option(c,v);return `<tr><td>${esc(c.title)}</td><td>${esc(o.label)}</td><td>${fmt(v)} / ${fmt(c.max)}</td></tr>`}).join("")}</tbody></table>`).join("");return `<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>${esc(title)}</title><style>body{font-family:Arial,sans-serif;margin:0;color:#172033}.wrap{padding:24px}.head{background:#14213d;color:#fff;padding:22px;border-radius:16px}.head p{color:#f4e6c0;font-weight:bold}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.grid div{border:1px solid #ddd;padding:12px;border-radius:12px}table{width:100%;border-collapse:collapse;margin:12px 0 22px}td,th{border:1px solid #ccc;padding:7px;font-size:12px;vertical-align:top}th{background:#f4e6c0}.pending{color:#777;background:#f7f7f7}button{padding:10px 14px;border:0;border-radius:10px;background:#14213d;color:#fff;font-weight:bold}@media print{button{display:none}.wrap{padding:0}.head{border-radius:0}}</style></head><body><div class="wrap"><div class="head"><h1>${esc(title)}</h1><p>${COURSE.institution} · ${COURSE.label} · ${COURSE.specialty} · ${COURSE.period}</p><p>Generado: ${dateTime(new Date())}</p></div><button onclick="window.print()">Imprimir / Guardar como PDF</button><div class="grid"><div>Total<br><b>${rs.length}</b></div><div>Evaluados<br><b>${done.length}</b></div><div>Pendientes<br><b>${rs.length-done.length}</b></div><div>Promedio<br><b>${done.length?fmt(avg):"—"} / 10</b></div></div><h2>Consolidado general</h2><table><thead><tr><th>No.</th><th>Estudiante</th><th>Estado</th><th>Puntaje</th><th>Observaciones</th><th>Comentario</th></tr></thead><tbody>${main}</tbody></table><h2>Detalle de rúbrica</h2>${det||"<p>No hay evaluaciones guardadas todavía.</p>"}</div></body></html>`}
function openPrint(all=true){const w=window.open("","_blank","noopener,noreferrer"),html=printable(rows(!all),all?"Rúbrica de Sustentación de Práctica Preprofesional":"Evaluaciones guardadas de sustentación");if(!w){download(html,"rubrica-sustentacion.html","text/html;charset=utf-8");return}w.document.open();w.document.write(html);w.document.close();toast("Reporte imprimible generado")}
function summary(){const rs=rows(false),done=rs.filter(x=>x.record.evaluated),avg=done.length?done.reduce((a,x)=>a+x.total,0)/done.length:0;const lines=["RESUMEN DE SUSTENTACIÓN DE PRÁCTICAS PREPROFESIONALES",`${COURSE.label} · ${COURSE.specialty}`,`Evaluados: ${done.length}/${rs.length}`,`Pendientes: ${rs.length-done.length}`,`Promedio: ${done.length?fmt(avg):"—"} / 10`,"","CALIFICACIONES"];done.forEach(({student:s,total:t})=>lines.push(`${s.n}. ${s.name}: ${fmt(t)} / 10`));const pending=rs.filter(x=>!x.record.evaluated);if(pending.length){lines.push("","PENDIENTES");pending.forEach(({student:s})=>lines.push(`${s.n}. ${s.name}`))}copyText(lines.join("\n"));toast("Resumen copiado")}
function renderHistory(){const rs=rows(true);els.history.innerHTML="";if(!rs.length){els.history.innerHTML='<div class="empty-state">No hay evaluaciones guardadas todavía.</div>';return}rs.forEach(({student:s,record:r,total:t})=>{const item=document.createElement("article");item.className="history-item";item.innerHTML=`<h3>${s.n}. ${esc(s.name)}</h3><p>Puntaje: <b>${fmt(t)} / 10</b> · Fecha: ${dateFmt(r.date)}</p><p>${esc(r.comment||r.notes.join(" · ")||"Sin comentario adicional")}</p>`;item.onclick=()=>{els.dialog.close();load(s.n);window.scrollTo({top:0,behavior:"smooth"})};els.history.appendChild(item)})}
function clearAll(){if(confirm("¿Borrar todas las evaluaciones guardadas de este dispositivo?")){store={};writeStore();load(1);renderHistory();toast("Registros borrados")}}
function init(){els.date.value=today();renderOptions();renderRubric();renderNotes();updateScore();status();stats();els.search.oninput=renderOptions;els.select.onchange=()=>load(els.select.value);els.activity.oninput=()=>!quiet&&draft(false);els.date.oninput=()=>!quiet&&draft(false);els.comment.oninput=()=>!quiet&&draft(false);$("#previousStudent").onclick=()=>load(Math.max(1,current-1));$("#nextStudent").onclick=()=>load(Math.min(STUDENTS.length,current+1));$("#resetCurrent").onclick=()=>{if(confirm("¿Restablecer la evaluación del estudiante actual?")){delete store[String(current)];writeStore();load(current);toast("Evaluación restablecida")}};$("#markExcellent").onclick=()=>{renderRubric({...record(),criteria:defaultCriteria()});draft(false);toast("Criterios marcados con puntaje máximo")};$("#clearNotes").onclick=()=>{document.querySelectorAll(".note-chip.active").forEach(b=>b.classList.remove("active"));els.comment.value="";draft(false);toast("Observaciones limpiadas")};$("#saveReport").onclick=()=>{draft(true);toast("Evaluación guardada")};$("#copyReport").onclick=()=>{copyText(report(true));toast("Reporte copiado")};$("#shareWhatsapp").onclick=()=>{window.open(`https://wa.me/?text=${encodeURIComponent(report(true))}`,"_blank","noopener,noreferrer");toast("Abriendo WhatsApp")};$("#exportClassCsv").onclick=()=>exportCsv(true);$("#exportClassCsvBar").onclick=()=>exportCsv(true);$("#exportClassPdf").onclick=()=>openPrint(true);$("#exportClassPdfBar").onclick=()=>openPrint(true);$("#copyClassSummary").onclick=summary;$("#openHistory").onclick=()=>{renderHistory();els.dialog.showModal()};$("#closeHistory").onclick=()=>els.dialog.close();$("#exportSavedCsv").onclick=()=>exportCsv(false);$("#exportSavedPdf").onclick=()=>openPrint(false);$("#clearHistory").onclick=clearAll}
init();
